x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "1"

x-python-app: &python-app
  image: fastapi-celery-scrapy:py310
  logging: *default-logging

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "127.0.0.1:5673:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rabbitmq_data:/var/lib/rabbitmq
    logging: *default-logging

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    logging: *default-logging

  api:
    <<: *python-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis

  worker:
    <<: *python-app
    command: celery -A app.celery_app worker --pool=solo -l info
    volumes:
      - ./src:/app
    depends_on:
      - rabbitmq
      - redis
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  rabbitmq_data:
